services:
  ecommerce:
    container_name: ecommerce
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ecommerce-db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3309:3306"
    volumes:
      - ecommerce:/var/lib/mysql
    networks:
      - ecommerce-network

  flyway:
    image: flyway/flyway
    container_name: ecommerce-flyway
    environment:
      - FLYWAY_URL=jdbc:mysql://ecommerce:3306/ecommerce-db
      - FLYWAY_USER=root
      - FLYWAY_PASSWORD=password
    volumes:
      - ./db/migrations:/flyway/sql
    depends_on:
      - ecommerce
    networks:
      - ecommerce-network

  ecommerce-api:
    container_name: ecommerce-remake
    image: gitpatrickv/ecommerce-remake:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - ecommerce-network
    depends_on:
      - ecommerce

volumes:
  ecommerce:

networks:
  ecommerce-network:
    driver: bridge
