spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: patrick
    url: jdbc:mysql://localhost:3306/ecommerce
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
application:
  security:
    jwt:
      secret-key: 6jZy59I3gNLH1Pj45sJT9/E0SSQUA1yNcAV1yZaXiwE
      expiration: 604800000
stripe:
  api:
    key: sk_test_51PchJnKrNg4CjtgGgbUYj56kZ2rKeWpFUnmUEPTLtJofgGDavpJO9t0RrLeNSUeNPWa5VmNWrdJOsbobNr4dyw1c00HSTVxG2m
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
